micronaut:
  application:
    name: orders
  server:
    port: 8082
    thread-selection: io
  executors:
    io:
      n-threads: 75
      type: fixed
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  data:
    pageable:
      sort-ignore-case: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  prometheus:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

mushop:
  messaging:
    subjects:
      orders: ${ORDERS_NEW:mushop-orders}
      shipments: ${ORDERS_SHIPPED:mushop-shipments}

# nats:
#   addresses:
#     - nats://${NATS_HOST:localhost}:${NATS_PORT:4222}
nats:
  default:
    server: nats://${NATS_HOST:localhost}:${NATS_PORT:4222}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
