FROM openjdk:16-alpine as builder

RUN apk update \
    && apk upgrade \
    && apk --no-cache add curl openssl perl

COPY import-aws-rds-certs.sh /certs/import-aws-rds-certs.sh

ARG trustStorePassword
RUN sh /certs/import-aws-rds-certs.sh


FROM ghcr.io/graalvm/graalvm-ce:java11-21.1.0

COPY --from=builder /certs/rds-truststore.jks /certs/rds-truststore.jks