CREATE TABLE PRODUCTS (
    sku VARCHAR2(20) NOT NULL,
    brand VARCHAR2(20),
    title VARCHAR2(40),
    description VARCHAR2(500),
    weight VARCHAR2(10),
    product_size VARCHAR2(25),
    colors VARCHAR2(20),
    qty NUMBER(10, 0),
    price FLOAT,
    image_url_1 VARCHAR2(50),
    image_url_2 VARCHAR2(50),
    PRIMARY KEY(sku)
);
CREATE TABLE CATEGORIES (
    category_id NUMBER(7,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(30),
    PRIMARY KEY(category_id)
);
CREATE TABLE PRODUCT_CATEGORY (
    product_category_id NUMBER(7,0) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    sku VARCHAR2(40),
    category_id NUMBER(7,0) NOT NULL,
    FOREIGN KEY (sku)
    REFERENCES PRODUCTS(sku),
    FOREIGN KEY(category_id)
    REFERENCES CATEGORIES(category_id),
    PRIMARY KEY(product_category_id)
);