micronaut:
  application:
    name: api
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
 
  security:
    authentication: session
    intercept-url-map:
      - pattern: /swagger/**
        access:
          - isAnonymous()
    endpoints:
      logout:
        path: /api/logout
        get-allowed: true
      login:
        enabled: true
  http:
    client:
      follow-redirects: true
  caches:
    discovery-client:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  session:
    http:
      header: true
      cookie: true
      redis:
        enabled: true
        namespace: 'mushop:sessions'
        write-mode: BACKGROUND
        enable-keyspace-events: true

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
  prometheus:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

nats:
  default:
    addresses:
      - "nats://${nats.host}:${nats.port}"