micronaut:
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

endpoints:
  prometheus:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS